version: '3'

networks:
  na_network:
    driver: bridge

services:
  na_web_app:
    image: "iqan/na-web-app:1.0.0"
    build: ./webApp
    container_name: na_web_app
    ports:
     - "8000:80"
    networks:
     - na_network
    restart: on-failure
    depends_on:
      - na_api_gateway
  na_api_gateway:
    image: "iqan/na-api-gateway:1.0.0"
    build: ./apiGateway
    container_name: na_api_gateway
    ports:
     - "3000:3000"
    networks:
     - na_network
    restart: on-failure
    depends_on:
      - na_user_profile
    environment:
      - USER_PROFILE_URL=http://na_user_profile:3001/
  na_user_profile:
    image: "iqan/na-user-profile:1.0.0"
    build: ./userProfileService
    container_name: na_user_profile
    ports:
     - "3001:3001"
    networks:
     - na_network
    environment:
     - MONGO_URL=mongodb://na_db:27017/notes-app
    restart: on-failure
    depends_on:
      - na_db
  na_db:
    image: "mongo:4.1.1-xenial"
    container_name: na_db
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - na_network
